name: Update-Waypoints

# Run this workflow every hour
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  create-json:
    name: Creates or updates waypoints.json
    runs-on: ubuntu-22.04
    env:
      DEFAULT_BRANCH: master
    defaults:
      run:
        shell: bash
    steps:
      - name: Prepare environment
        run: |
          sudo apt-get --yes update
          sudo apt-get --yes install python3-pip
          sudo pip3 install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
          sudo pip3 install -U pip setuptools
          sudo pip3 install --use-pep517 googlemaps
          sudo pip3 install pandas
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set environment variables and update waypoints.json
        run: |
          export SPREADSHEET_ID="$GOOGLE_SPREADSHEET_ID"
          export GEOCODING_API_KEY="$GOOGLE_GEOCODING_API_KEY"
          echo "$GOOGLE_SERVICE_ACCOUNT" > credentials.json
          python3 update_waypoints.py
        env:
          GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
          GOOGLE_GEOCODING_API_KEY: ${{ secrets.GOOGLE_GEOCODING_API_KEY }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      - name: Test step
        run: |
          cat temp-waypoints.json
      # - name: Check for changes
      #   run: |
      #     if git diff --exit-code; then
      #       echo "changes_exist=false" >> $GITHUB_ENV
      #     else
      #       echo "changes_exist=true" >> $GITHUB_ENV
      #     fi
      # - name: Add and commit changes to waypoints.json
      #   if: ${{ env.changes_exist == 'true' || env.already_exists == 'false' }}
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add src/waypoints.json
      #     git add public/static/waypoints.json
      #     git commit -m "Update waypoints.json with new rows"
      # - name: Push changes to repository
      #   if: ${{ env.changes_exist == 'true' || env.already_exists == 'false' }}
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
